//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Tryes = new HashSet<Trye>();
        }
    
        public int QuestionID { get; set; }
        public int TestID { get; set; }
        public string TextQuestion { get; set; }
        public int Answer { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual ICollection<Trye> Tryes { get; set; }
    }
}
