//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.Questions = new HashSet<Question>();
            this.Tryes = new HashSet<Trye>();
        }
    
        public int TestID { get; set; }
        public int CountQuestion { get; set; }
        public int AuthorID { get; set; }
        public string Discipline { get; set; }
        public string Theme { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Trye> Tryes { get; set; }
    }
}
