//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trye
    {
        public int TryID { get; set; }
        public int UID { get; set; }
        public int TestID { get; set; }
        public int QuestionID { get; set; }
        public int Answer { get; set; }
        public bool WriteAnswer { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
        public virtual Question Question { get; set; }
    }
}
