//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ct
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Tests = new HashSet<Test>();
            this.Tryes = new HashSet<Trye>();
        }
    
        public int UID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public bool Teacher { get; set; }
    
        public virtual ICollection<Test> Tests { get; set; }
        public virtual ICollection<Trye> Tryes { get; set; }
    }
}
